import{a as v,S,i as l}from"./assets/vendor-B4VkUtbg.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const w="57885931-70be65b5a26a36e09f32ff59f",q="https://pixabay.com/api/";function f(o){return v.get(q,{params:{key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data)}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:r,views:n,comments:L,downloads:b})=>`
          <li class="gallery-item">
            <a href="${a}">
              <img src="${i}" alt="${e}" />
            </a>
            <div class="image-info">
              <p><b>Likes:</b> ${r}</p>
              <p><b>Views:</b> ${n}</p>
              <p><b>Comments:</b> ${L}</p>
              <p><b>Downloads:</b> ${b}</p>
            </div>
          </li>
        `).join("");m.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){m.innerHTML=""}function p(){h.classList.remove("is-hidden")}function y(){h.classList.add("is-hidden")}const d=document.querySelector(".form"),s=document.querySelector(".load-more");let u="",c=1;s.classList.add("is-hidden");d.addEventListener("submit",o=>{o.preventDefault();const t=d.elements["search-text"].value.trim();if(!t){l.warning({message:"Please enter a search query!",position:"topRight"});return}u=t,c=1,s.classList.add("is-hidden"),$(),p(),f(u).then(i=>{if(i.hits.length===0){l.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(i.hits),c*15<i.totalHits&&s.classList.remove("is-hidden")}).catch(()=>{l.error({message:"Something went wrong. Please try again later!",position:"topRight"})}).finally(()=>{y()}),d.reset()});s.addEventListener("click",()=>{c+=1,p(),s.classList.add("is-hidden"),f(u).then(o=>{g(o.hits),c*15<o.totalHits&&s.classList.remove("is-hidden");const t=document.querySelectorAll(".gallery-item");t.length>0&&t[t.length-o.hits.length].scrollIntoView({behavior:"smooth",block:"start"})}).catch(()=>{l.error({message:"Something went wrong. Please try again later!",position:"topRight"})}).finally(()=>{y()})});
//# sourceMappingURL=index.js.map
